services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: contract-parser-backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./backend/uploads:/app/uploads
    environment:
      - MONGODB_URL=mongodb://mongo:27017/
      - MONGODB_DB=contract_parser
    depends_on:
      - mongo
    networks:
      - contract-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: contract-parser-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      - backend
    networks:
      - contract-network

  mongo:
    image: mongo:6.0
    container_name: mongo
    restart: always
    volumes:
      - mongo-data:/data/db
    networks:
      - contract-network

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=password
    depends_on:
      - mongo
    networks:
      - contract-network

networks:
  contract-network:
    driver: bridge

volumes:
  mongo-data:
